### ISSUE TITLE
compatability with spongeforge

### ISSUE THREAD

**Issue by thebikwirm** [ItsBlackGear/Platform#3]
```java
at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.spongeforge.core.json:minecraftforge.fml.ModContainerMixin_Forge,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_431] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_431] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_431] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_431] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_431] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_431] {}
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [platform.mixins.json:core.networking.ServerLoginPacketListenerImplMixin] from phase [DEFAULT] in config [platform.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	... 44 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/network/login/ServerLoginNetHandler::platform$handlePlayTransitionNormal with priority 998 cannot inject into net/minecraft/network/login/ServerLoginNetHandler::func_147326_c()V merged by org.spongepowered.common.mixin.core.server.network.ServerLoginPacketListenerImplMixin with priority 1101 [PREINJECT Applicator Phase -> platform.mixins.json:core.networking.ServerLoginPacketListenerImplMixin -> Prepare Injections ->  -> handler$cdc000$platform$handlePlayTransitionNormal(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
```

**Comment by thebikwirm** [comment]
need sponge forge server side but just crashes
https://github.com/ItsBlackGear/Platform/blob/f8891972fb5d7ebaeb0ee8629f4ad13d8792f65a/forge/src/main/java/com/blackgear/platform/core/mixin/core/networking/ServerLoginPacketListenerImplMixin.java#L24C2-L26C51
only when sponge is enabled

**Comment by thebikwirm** [comment]
this is for 16.5 forge, let me know if more info is needed

**Comment by ItsBlackGear** [comment]
gotcha! i'll take a look into this

**Comment by thebikwirm** [comment]
thx

**Comment by thebikwirm** [comment]
any word on this?
look to start a new world for my server and would like to use spongeforge
was this merged/solved in newest release?

**Comment by ItsBlackGear** [comment]
I've taken a look into this, however it seems that the issue is caused by the networking 🤔 i'll keep the issue open and update you about it!

**Comment by ItsBlackGear** [comment]
Issue has been fixed on Platform 1.2.2
